<?php

namespace ContainerPRANDGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBathControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6o1ti.z.App\Controller\BathController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6o1ti.z.App\\Controller\\BathController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bathRepository' => ['privates', 'App\\Repository\\BathRepository', 'getBathRepositoryService', true],
        ], [
            'bathRepository' => 'App\\Repository\\BathRepository',
        ]))->withContext('App\\Controller\\BathController::index()', $container);
    }
}
