<?php

namespace ContainerPRANDGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadControllerhistoriqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A94TATw.App\Controller\LeadController::historique()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A94TATw.App\\Controller\\LeadController::historique()'] = ($container->privates['.service_locator.A94TATw'] ?? $container->load('get_ServiceLocator_A94TATwService'))->withContext('App\\Controller\\LeadController::historique()', $container);
    }
}
