<?php

namespace ContainerPRANDGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zd_rQS7.App\Controller\LeadController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zd_rQS7.App\\Controller\\LeadController::delete()'] = ($container->privates['.service_locator.Zd_rQS7'] ?? $container->load('get_ServiceLocator_ZdRQS7Service'))->withContext('App\\Controller\\LeadController::delete()', $container);
    }
}
