<?php

namespace ContainerPRANDGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fYfHD6l.App\Controller\LeadController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fYfHD6l.App\\Controller\\LeadController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'leadRepository' => ['privates', 'App\\Repository\\LeadRepository', 'getLeadRepositoryService', true],
        ], [
            'leadRepository' => 'App\\Repository\\LeadRepository',
        ]))->withContext('App\\Controller\\LeadController::deleteAll()', $container);
    }
}
