<?php

namespace ContainerPRANDGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanningControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fZNsVOM.App\Controller\PlanningController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fZNsVOM.App\\Controller\\PlanningController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planning' => ['privates', '.errored..service_locator.fZNsVOM.App\\Entity\\Planning', NULL, 'Cannot autowire service ".service_locator.fZNsVOM": it needs an instance of "App\\Entity\\Planning" but this type has been excluded in "config/services.yaml".'],
        ], [
            'planning' => 'App\\Entity\\Planning',
        ]))->withContext('App\\Controller\\PlanningController::show()', $container);
    }
}
