<?php

namespace ContainerPRANDGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanningControllereditInlineUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hcS_uG9.App\Controller\PlanningController::editInlineUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hcS_uG9.App\\Controller\\PlanningController::editInlineUser()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planning' => ['privates', '.errored..service_locator.hcS_uG9.App\\Entity\\Planning', NULL, 'Cannot autowire service ".service_locator.hcS_uG9": it needs an instance of "App\\Entity\\Planning" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'logger', 'getLoggerService', false],
        ], [
            'planning' => 'App\\Entity\\Planning',
            'entityManager' => '?',
            'logger' => '?',
        ]))->withContext('App\\Controller\\PlanningController::editInlineUser()', $container);
    }
}
