<?php

namespace ContainerBZTQeFS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KL49AqyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KL49Aqy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KL49Aqy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bath' => ['privates', '.errored..service_locator.KL49Aqy.App\\Entity\\Bath', NULL, 'Cannot autowire service ".service_locator.KL49Aqy": it needs an instance of "App\\Entity\\Bath" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'bath' => 'App\\Entity\\Bath',
            'entityManager' => '?',
        ]);
    }
}
