<?php

namespace ContainerBZTQeFS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBathControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JG8cafT.App\Controller\BathController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JG8cafT.App\\Controller\\BathController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bath' => ['privates', '.errored..service_locator.JG8cafT.App\\Entity\\Bath', NULL, 'Cannot autowire service ".service_locator.JG8cafT": it needs an instance of "App\\Entity\\Bath" but this type has been excluded in "config/services.yaml".'],
        ], [
            'bath' => 'App\\Entity\\Bath',
        ]))->withContext('App\\Controller\\BathController::show()', $container);
    }
}
