<?php

namespace ContainerBZTQeFS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHoraireControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y0yu8rK.App\Controller\HoraireController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y0yu8rK.App\\Controller\\HoraireController::delete()'] = ($container->privates['.service_locator.y0yu8rK'] ?? $container->load('get_ServiceLocator_Y0yu8rKService'))->withContext('App\\Controller\\HoraireController::delete()', $container);
    }
}
