<?php

namespace ContainerBZTQeFS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHoraire2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.y0yu8rK.App\Entity\Horaire' shared service.
     *
     * @return \App\Entity\Horaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.y0yu8rK": it needs an instance of "App\\Entity\\Horaire" but this type has been excluded in "config/services.yaml".');
    }
}
