<?php

namespace ContainerBZTQeFS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadControllerdeleteTotalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S0RQ0dn.App\Controller\LeadController::delete_total()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S0RQ0dn.App\\Controller\\LeadController::delete_total()'] = ($container->privates['.service_locator.S0RQ0dn'] ?? $container->load('get_ServiceLocator_S0RQ0dnService'))->withContext('App\\Controller\\LeadController::delete_total()', $container);
    }
}
