<?php

namespace ContainerBZTQeFS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LRaAgvH.App\Controller\LeadController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LRaAgvH.App\\Controller\\LeadController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lead' => ['privates', '.errored..service_locator.LRaAgvH.App\\Entity\\Lead', NULL, 'Cannot autowire service ".service_locator.LRaAgvH": it needs an instance of "App\\Entity\\Lead" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lead' => 'App\\Entity\\Lead',
        ]))->withContext('App\\Controller\\LeadController::show()', $container);
    }
}
