<?php

namespace ContainerBZTQeFS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanningControllerplanningPartService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d4Yeg7K.App\Controller\PlanningController::planning_part()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d4Yeg7K.App\\Controller\\PlanningController::planning_part()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planningRepository' => ['privates', 'App\\Repository\\PlanningRepository', 'getPlanningRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'planningRepository' => 'App\\Repository\\PlanningRepository',
            'userRepository' => 'App\\Repository\\UsersRepository',
        ]))->withContext('App\\Controller\\PlanningController::planning_part()', $container);
    }
}
