<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lead extends \App\Entity\Lead implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'chauffage' => [parent::class, 'chauffage', null],
        "\0".parent::class."\0".'commentaire' => [parent::class, 'commentaire', null],
        "\0".parent::class."\0".'departement' => [parent::class, 'departement', null],
        "\0".parent::class."\0".'heure_creation' => [parent::class, 'heure_creation', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_enregistrement' => [parent::class, 'id_enregistrement', null],
        "\0".parent::class."\0".'nom_complet' => [parent::class, 'nom_complet', null],
        "\0".parent::class."\0".'plannings' => [parent::class, 'plannings', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'technicien' => [parent::class, 'technicien', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        'chauffage' => [parent::class, 'chauffage', null],
        'commentaire' => [parent::class, 'commentaire', null],
        'departement' => [parent::class, 'departement', null],
        'heure_creation' => [parent::class, 'heure_creation', null],
        'id' => [parent::class, 'id', null],
        'id_enregistrement' => [parent::class, 'id_enregistrement', null],
        'nom_complet' => [parent::class, 'nom_complet', null],
        'plannings' => [parent::class, 'plannings', null],
        'status' => [parent::class, 'status', null],
        'technicien' => [parent::class, 'technicien', null],
        'telephone' => [parent::class, 'telephone', null],
        'users' => [parent::class, 'users', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
