<?php

namespace ContainerUT2BlN3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4wYDPEYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4wYDPEY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4wYDPEY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lead' => ['privates', '.errored..service_locator.4wYDPEY.App\\Entity\\Lead', NULL, 'Cannot autowire service ".service_locator.4wYDPEY": it needs an instance of "App\\Entity\\Lead" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'lead' => 'App\\Entity\\Lead',
            'entityManager' => '?',
            'userRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
