<?php

namespace ContainerUT2BlN3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A94TATwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A94TATw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A94TATw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'leadRepository' => ['privates', 'App\\Repository\\LeadRepository', 'getLeadRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'leadRepository' => 'App\\Repository\\LeadRepository',
            'userRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
