<?php

namespace ContainerUT2BlN3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBath2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KL49Aqy.App\Entity\Bath' shared service.
     *
     * @return \App\Entity\Bath
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KL49Aqy": it needs an instance of "App\\Entity\\Bath" but this type has been excluded in "config/services.yaml".');
    }
}
