<?php

namespace ContainerUT2BlN3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHoraireControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BGMSzel.App\Controller\HoraireController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BGMSzel.App\\Controller\\HoraireController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'horaire' => ['privates', '.errored..service_locator.BGMSzel.App\\Entity\\Horaire', NULL, 'Cannot autowire service ".service_locator.BGMSzel": it needs an instance of "App\\Entity\\Horaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'horaire' => 'App\\Entity\\Horaire',
        ]))->withContext('App\\Controller\\HoraireController::show()', $container);
    }
}
