<?php

namespace ContainerUT2BlN3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadControllereditInlinHistoriqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4wYDPEY.App\Controller\LeadController::editInlinHistorique()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4wYDPEY.App\\Controller\\LeadController::editInlinHistorique()'] = ($container->privates['.service_locator.4wYDPEY'] ?? $container->load('get_ServiceLocator_4wYDPEYService'))->withContext('App\\Controller\\LeadController::editInlinHistorique()', $container);
    }
}
