<?php

namespace ContainerUT2BlN3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanningControllernewleadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.giuinMt.App\Controller\PlanningController::newlead()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.giuinMt.App\\Controller\\PlanningController::newlead()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logger' => ['privates', 'logger', 'getLoggerService', false],
        ], [
            'entityManager' => '?',
            'logger' => '?',
        ]))->withContext('App\\Controller\\PlanningController::newlead()', $container);
    }
}
