<?php

namespace ContainerUT2BlN3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanningControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1Q7sNhR.App\Controller\PlanningController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1Q7sNhR.App\\Controller\\PlanningController::edit()'] = ($container->privates['.service_locator.1Q7sNhR'] ?? $container->load('get_ServiceLocator_1Q7sNhRService'))->withContext('App\\Controller\\PlanningController::edit()', $container);
    }
}
